### ISSUE TITLE
Scope of cayaml

### ISSUE THREAD

**Issue by Mark1626** [karuppiah7890/cayaml#1]
## Usecase:

1. Let's say I have to do repeated POST to a server

request.template.yml

```yml
name: curl
flags:
  - name: -H
    value: 'Content-Type: {{ dataType }}'
  - name: -X
    value: POST
  - name: -d
    value: {{ data }}
arguments:
  - example.com
```

Now I should be able to do `cayaml request.template.yaml data` and a curl request to the URL should be possible. This should save time for me to exec curl
